// export-tasks.mjs — round-trip: rebuild a list's tasks.json from a SAVED TiddlyWiki HTML.
//
// Use case: an admin edits the task structure live in the wiki (adds/removes tasks or
// sections, marks tasks shared), then saves a snapshot from the wiki ("save snapshot for
// offline use" / the browser's save). This reads that HTML and regenerates the *structure*
// (sections, tasks, group, shared) back into tasks.json so the repo stays the source of truth.
//
// It exports STRUCTURE ONLY — never runtime data (done-states, comments, per-person ticks);
// those live in the wiki, never in the repo.
//
//   node export-tasks.mjs <saved-wiki.html> [path/to/tasks.json]
//
// Defaults: output -> moving-house-wiki/tasks.json (preserving its existing "list" config).
import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const HERE = dirname(fileURLToPath(import.meta.url));
const htmlPath = process.argv[2];
const outPath = process.argv[3] || resolve(HERE, "moving-house-wiki", "tasks.json");

if (!htmlPath) {
  console.error("Usage: node export-tasks.mjs <saved-wiki.html> [tasks.json]");
  process.exit(1);
}

const html = readFileSync(htmlPath, "utf8");
const re = /<script class="tiddlywiki-tiddler-store"[^>]*>([\s\S]*?)<\/script>/g;
let m, all = [];
while ((m = re.exec(html))) { try { all.push(...JSON.parse(m[1])); } catch (e) { /* skip */ } }
if (!all.length) { console.error("No tiddler store found in", htmlPath); process.exit(1); }

const hasTag = (t, tag) => (t.tags || "").split(" ").filter(Boolean).includes(tag)
  || / /.test(t.tags || "") && (t.tags || "").includes(`[[${tag}]]`);
const num = (v) => (parseInt(v, 10) || 0);

// Sections ordered by their `order` field.
const sections = all.filter(t => hasTag(t, "task-section")).sort((a, b) => num(a.order) - num(b.order));
const tasks = all.filter(t => hasTag(t, "task")).sort((a, b) => num(a.order) - num(b.order));

// Preserve the existing list config if the output already exists.
let listCfg = { title: "Tasks", bag: "tasks", recipe: "tasks", description: "Task list", membersTiddler: "$:/moving-house/members" };
try { listCfg = { ...listCfg, ...(JSON.parse(readFileSync(outPath, "utf8")).list || {}) }; } catch { /* new file */ }

// Group tasks by their `section` field (never drop a task). Order sections by the
// task-section tiddlers' order, then append any section that has tasks but no heading tiddler.
const bySection = new Map();
for (const t of tasks) {
  if (!bySection.has(t.section)) bySection.set(t.section, []);
  bySection.get(t.section).push(t);
}
const ordered = [...new Set([...sections.map(s => s.title), ...bySection.keys()])].filter(n => bySection.has(n));
const toItem = (t) => {
  const o = {};
  if (t.group) o.group = t.group;
  if (t.shared === "yes" || t.shared === true) o.shared = true;
  return Object.keys(o).length ? { title: t.title, ...o } : t.title;
};
const out = {
  list: listCfg,
  _comment: "A task is a string, or {title, group?, shared?}. Regenerated by export-tasks.mjs.",
  sections: ordered.map(name => ({ name, tasks: bySection.get(name).map(toItem) })),
};

writeFileSync(outPath, JSON.stringify(out, null, 2) + "\n");
const sharedN = tasks.filter(t => t.shared === "yes").length;
console.log(`Wrote ${outPath}: ${out.sections.length} sections, ${tasks.length} tasks (${sharedN} shared).`);
console.log("Now run:  node moving-house-wiki/build-seed.mjs   (then deploy per CUSTOMISING.md).");
